version: "3"
services:

  auth_database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_root_password
      POSTGRES_DB: auth_db
    networks:
      - auth
    ports:
      - '5432'
    volumes:
      - ./auth/auth_sql:/docker-entrypoint-initdb.d

  auth_app:
    image: auth_app
    environment:
      DATABASE_HOST: auth_database
      DATABASE_PORT: 5432
      PRODUCTION: 5000
    networks:
      - auth
    ports:
      - 5000:5000

  main_database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_root_password
      POSTGRES_DB: main_db
    networks:
      - main
    ports:
      - '5432'
    volumes:
      - ./main/main_sql:/docker-entrypoint-initdb.d

  main_app:
    image: main_app
    environment:
      DATABASE_HOST: main_database
      DATABASE_PORT: 5432
      PRODUCTION: 5001
    networks:
      - main
    ports:
      - 5001:5000

networks:
  auth:
  main: